// <auto-generated />
using System;
using Lab12RelationalDatabases.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lab12RelationalDatabases.Migrations
{
    [DbContext(typeof(AsyncHotelsDbContext))]
    [Migration("20200406190505_dbseeding")]
    partial class dbseeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lab12RelationalDatabases.Models.Amenities", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Coffee Maker"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Minifridge"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Minibar"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Balcony"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Waterfront View"
                        });
                });

            modelBuilder.Entity("Lab12RelationalDatabases.Models.Hotel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            City = "Seattle",
                            Name = "Seattle Async",
                            Phone = "206-555-4509",
                            State = "Washington",
                            StreetAddress = "443 3rd Ave"
                        },
                        new
                        {
                            ID = 2,
                            City = "Maui",
                            Name = "Maui Async",
                            Phone = "808-555-4510",
                            State = "Hawaii",
                            StreetAddress = "445 Ka'anapali Blvd"
                        },
                        new
                        {
                            ID = 3,
                            City = "Dubuque",
                            Name = "Dubuque Async",
                            Phone = "563-555-4511",
                            State = "Iowa",
                            StreetAddress = "447 7th Ave"
                        },
                        new
                        {
                            ID = 4,
                            City = "Steamboat Springs",
                            Name = "Steamboat Springs Async",
                            Phone = "970-555-4513",
                            State = "Colorado",
                            StreetAddress = "449 9th Ave"
                        },
                        new
                        {
                            ID = 5,
                            City = "Santa Monica",
                            Name = "Santa Monica Async",
                            Phone = "310-555-4509",
                            State = "California",
                            StreetAddress = "451 Santa Monica Blvd"
                        });
                });

            modelBuilder.Entity("Lab12RelationalDatabases.Models.HotelRoom", b =>
                {
                    b.Property<int>("HotelID")
                        .HasColumnType("int");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.Property<bool>("PetFriendly")
                        .HasColumnType("bit");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.HasKey("HotelID", "RoomID");

                    b.HasIndex("HotelID")
                        .IsUnique();

                    b.HasIndex("RoomID");

                    b.ToTable("HotelRooms");

                    b.HasData(
                        new
                        {
                            HotelID = 1,
                            RoomID = 2,
                            PetFriendly = true,
                            Rate = 200m,
                            RoomNumber = 503
                        },
                        new
                        {
                            HotelID = 3,
                            RoomID = 1,
                            PetFriendly = false,
                            Rate = 180m,
                            RoomNumber = 404
                        });
                });

            modelBuilder.Entity("Lab12RelationalDatabases.Models.Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Layout")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Layout = 0,
                            Name = "Studio"
                        },
                        new
                        {
                            ID = 2,
                            Layout = 1,
                            Name = "One Bedroom"
                        },
                        new
                        {
                            ID = 3,
                            Layout = 2,
                            Name = "Two Bedroom"
                        },
                        new
                        {
                            ID = 4,
                            Layout = 3,
                            Name = "Studio (ADA Compliant)"
                        },
                        new
                        {
                            ID = 5,
                            Layout = 4,
                            Name = "One Bedroom (ADA Compliant)"
                        },
                        new
                        {
                            ID = 6,
                            Layout = 5,
                            Name = "Two Bedroom (ADA Compliant)"
                        });
                });

            modelBuilder.Entity("Lab12RelationalDatabases.Models.RoomAmenities", b =>
                {
                    b.Property<string>("AmenitiesID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.Property<int?>("AmenitiesID1")
                        .HasColumnType("int");

                    b.HasKey("AmenitiesID", "RoomID");

                    b.HasIndex("AmenitiesID1");

                    b.HasIndex("RoomID");

                    b.ToTable("RoomAmenities");
                });

            modelBuilder.Entity("Lab12RelationalDatabases.Models.HotelRoom", b =>
                {
                    b.HasOne("Lab12RelationalDatabases.Models.Hotel", "Hotel")
                        .WithOne("HotelRoom")
                        .HasForeignKey("Lab12RelationalDatabases.Models.HotelRoom", "HotelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab12RelationalDatabases.Models.Room", "Room")
                        .WithMany("HotelRoom")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lab12RelationalDatabases.Models.RoomAmenities", b =>
                {
                    b.HasOne("Lab12RelationalDatabases.Models.Amenities", "Amenities")
                        .WithMany("RoomAmenities")
                        .HasForeignKey("AmenitiesID1");

                    b.HasOne("Lab12RelationalDatabases.Models.Room", "Room")
                        .WithMany("RoomAmenities")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
